# Generated by Django 3.2.12 on 2022-02-21 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Activate this flag for these users.",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
    ]
