# Generated by Django 3.2.12 on 2022-02-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="coursetask",
            options={
                "verbose_name": "Course Task",
                "verbose_name_plural": "Course Tasks",
            },
        ),
    ]
