# Generated by Django 3.2.12 on 2022-02-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="grade_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.gradelevel",
                verbose_name="grado escolar",
            ),
        ),
    ]
