# Generated by Django 3.2.12 on 2022-02-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_grade_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="days_of_weeks",
            field=models.PositiveIntegerField(
                default=31,
                help_text="días de la semana en la que hay sesión",
                verbose_name="días de la semana",
            ),
        ),
    ]
