# Generated by Django 3.2.12 on 2022-02-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_auto_20220219_2358"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=256, verbose_name="name"),
        ),
    ]
