# Generated by Django 3.2.12 on 2022-02-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_days_of_weeks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="days_of_weeks",
            new_name="days_of_week",
        ),
    ]
