# Generated by Django 3.2.12 on 2022-02-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0010_auto_20220220_0105"),
        ("courses", "0003_alter_course_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Curso", "verbose_name_plural": "Cursos"},
        ),
        migrations.AlterModelOptions(
            name="coursetask",
            options={
                "verbose_name": "Tarea del Curso",
                "verbose_name_plural": "Tareas de los Cursos",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="grade_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.gradelevel",
                verbose_name="grado escolar",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=256, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="coursetask",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="curso",
            ),
        ),
        migrations.AlterField(
            model_name="coursetask",
            name="description",
            field=models.TextField(verbose_name="descripción"),
        ),
    ]
