# Generated by Django 3.2.12 on 2022-03-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_alter_gradelevel_school_year"),
        ("courses", "0004_rename_days_of_weeks_course_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="grade_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="schools.gradelevel",
                verbose_name="grado escolar",
            ),
        ),
    ]
