# Generated by Django 3.2.12 on 2022-02-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_auto_20220223_0032"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
            },
        ),
    ]
