# Generated by Django 3.2.12 on 2022-02-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_coursework"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursework",
            options={
                "verbose_name": "Trabajo finalizado",
                "verbose_name_plural": "Trabajos finalizados",
            },
        ),
    ]
