# Generated by Django 3.2.12 on 2022-03-01 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_alter_gradelevel_school_year"),
        ("students", "0005_alter_coursework_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="schools.school",
                verbose_name="escuela",
            ),
        ),
    ]
