# Generated by Django 3.2.12 on 2022-02-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_school_admin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolAdmin",
        ),
    ]
