# Generated by Django 3.2.12 on 2022-02-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_delete_schooladmin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "school", "verbose_name_plural": "schools"},
        ),
    ]
