# Generated by Django 3.2.12 on 2022-02-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_schoolyear_days_of_weeks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolyear",
            name="days_of_weeks",
            field=models.PositiveIntegerField(
                default=31,
                help_text="días de la semana en la que hay sesión",
                verbose_name="días de la semana",
            ),
        ),
    ]
