# Generated by Django 3.2.12 on 2022-02-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_alter_school_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "escuela", "verbose_name_plural": "escuelas"},
        ),
    ]
