# Generated by Django 3.2.12 on 2022-02-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_alter_schoolyear_days_of_weeks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schoolyear",
            old_name="days_of_weeks",
            new_name="days_of_week",
        ),
    ]
