# Generated by Django 3.2.12 on 2022-03-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_rename_days_of_weeks_schoolyear_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradelevel",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_levels",
                to="schools.schoolyear",
                verbose_name="año escolar",
            ),
        ),
    ]
