# Generated by Django 3.2.12 on 2022-02-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_alter_school_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={},
        ),
    ]
