# Generated by Django 3.2.12 on 2022-02-20 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0009_auto_20220219_2358"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradelevel",
            options={
                "verbose_name": "Grado Escolar",
                "verbose_name_plural": "Grados Escolares",
            },
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "Escuela", "verbose_name_plural": "Escuelas"},
        ),
        migrations.AlterModelOptions(
            name="schoolyear",
            options={
                "verbose_name": "Año Escolar",
                "verbose_name_plural": "Años Escolares",
            },
        ),
        migrations.AlterField(
            model_name="gradelevel",
            name="name",
            field=models.CharField(max_length=128, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="gradelevel",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.schoolyear",
                verbose_name="año escolar",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="admin",
            field=models.ForeignKey(
                help_text="Administrador de la Escuela",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="end_date",
            field=models.DateField(verbose_name="fecha de culminación"),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.school",
                verbose_name="escuela",
            ),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="start_date",
            field=models.DateField(verbose_name="fecha de inicio"),
        ),
    ]
