name: Tests Runner
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Cache Python packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}


      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install packages
        run: |
          cat requirements.txt | grep -v psycopg2 > requirements-no-pg.txt
          pip install -r requirements-no-pg.txt requirements-dev.txt
          pip install psycopg2-binary

      - name: Run publisher
        run: python manage.py test