name: Tests Runner
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Cache Python packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}

      - name: Install Postgres dev headers for pg_config
        run: sudo apt install libpq-dev

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

       - name: Install packages
        run: |
          sudo apt install \
          # Postgres dev headers for pg_config
          libpq-dev \
          # Graphviz support
          python3-dev graphviz libgraphviz-dev

      - name: Test it
        run: python manage.py test
        env:
          SECRET_KEY: 'a secret to everybody'